name: Events Demo 1
on:
    pull_request:
      types:
        - opened
    workflow_dispatch:
    push:
      branches:
#       - master
        - 'bug*'
      paths:
        - 'src/App.jsx'
#     paths-ignore:
#       - '.github/workflows/*'
jobs:
  test-and-build:
    runs-on:  ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3.5.0
      - name: Install the dependencies
        run:  npm ci
      - name: Lint the code
        run:  npm run lint
      - name: Test the code
        run:  npm run test
      - name: Build the package
        run:  npm run build
      - name: Upload the package
        uses: actions/upload-artifact@v3.1.2
        with:
          name: package-files
          path: |
            dist
            vite.config.js
  deploy:    
    needs: test-and-build
    runs-on: ubuntu-latest    
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Download the package
        uses: actions/download-artifact@v3.0.2
        with:
          name: package-files
      - name: Output package content
        run:  ls
      - name: Deploy project
        run: echo "Deploying..."